[package]
name = "redox-iou"
version = "0.0.0"
authors = ["4lDO2 <4lDO2@protonmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["executor", "io_uring", "redox", "futures", "async"]
categories = ["asynchronous", "os"]
description = "Redox's own liburing alternative"
documentation = "https://docs.rs/redox-iou"
repository = "https://gitlab.redox-os.org/redox-os/redox-iou"
readme = "README.md"
homepage = "https://redox-os.org/"

[features]
buffer_pool = ["cranelift-bforest", "redox-buffer-pool"]
default = ["buffer_pool"]

[dependencies]
async-task = "3"
bitflags = "1.2"
cranelift-bforest = { version = "0.65", optional = true }
crossbeam-queue = "0.2"
either = "1.5"
futures = "0.3"
log = "0.4"
once_cell = "1.4"
parking_lot = { version = "0.11", features = ["nightly"] }
pin-utils = "0.1"
redox_syscall = { git = "https://gitlab.redox-os.org/4lDO2/syscall.git", branch = "io_uring" }

redox-buffer-pool = { path = "redox-buffer-pool", version = "0.1", optional = true }

[workspace]
members = [
    "redox-buffer-pool",
]
